# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- development

variables:
  group: New variable group 20-Aug
  azureServiceConnectionId: '2168b0e6-75d6-4ea0-8c10-455d0f13403d'
  webAppName: 'Testing-Bckend'
  vmImageName: 'ubuntu-latest'
  environmentName: 'Testing-Bckend'
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      name: ATS-Pool
    steps:

    - script: |
        python --version
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install setup
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Set up Python environment and install dependencies"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      name: ATS-Pool
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:

          - script: |
              python --version
            displayName: 'Check Python version on deploy agent'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : Testing-Bckend'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
